---
- name: Configure NTP Server
  hosts: ntp
  gather_facts: true
  become: true
  roles:
    - role: chrony
  tags: [ntp]

- name: Configure Application Server
  hosts: app
  gather_facts: true
  become: true
  roles:
    - role: nginx
  tags: [app]

- name: Configure Database Server
  hosts: db
  gather_facts: true
  become: true
  roles:
    - role: postgresql
  tags: [db]

- name: Deployment Summary
  hosts: app
  gather_facts: false
  run_once: true
  tags: [summary, always]
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Print Nginx Summary
      ansible.builtin.debug:
        msg: |
          ========================================
              APP DEPLOYMENT SUMMARY
          ========================================
          Version  : {{ ansible_facts.packages['nginx'][0]['version'] | default('Not found') }}
          Access   : {{ nginx_access_log }}
          Error    : {{ nginx_error_log }}
          ========================================